### ISSUE TITLE
unnecessary function in lib/utils.lua

### ISSUE THREAD

**Issue by thacuber2a03** [GDAC-at-Davis/AltCtrlLab-Pico8-Console#1]
first off: thanks for using my library! it makes me pretty happy to see people using my software
second:
https://github.com/GDAC-at-Davis/AltCtrlLab-Pico8-Console/blob/dc931ad8c65e4a115ecd3e7cb37c9c834bbd4b8b/lib/utils.lua#L22
this function isn't necessary, as `vector` can already do what this function does:
https://github.com/GDAC-at-Davis/AltCtrlLab-Pico8-Console/blob/dc931ad8c65e4a115ecd3e7cb37c9c834bbd4b8b/lib/utils.lua#L4
it enough to call it without parameters to get a zero vector :)

**Comment by DoubleBrackets** [comment]
Nice to see you here :O 
Thanks for the catch!
